#########################################################################################
##################################   APPLICATION   ######################################
version: '3'
services:
  gateway:
    build:
      ./gateway
    ports:
      - 8080:8080
  processor:
    build:
      ./processor
    expose:
      - 1-65535